apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    http_port = 3000
    root_url = http://10.6.50.200:30300/
    app_title = Dashboard
    
    [security]
    admin_user = admin
    admin_password = grafana123
    
    [users]
    allow_sign_up = false
    auto_assign_org = true
    auto_assign_org_role = Viewer
    
    [auth]
    disable_login_form = false
    disable_signout_menu = false
    
    
    [log]
    mode = console
    level = info
    
    [analytics]
    reporting_enabled = false
    check_for_updates = false
    
    [branding]
    app_title = Dashboard
    login_title = Dashboard
    login_subtitle = 
    footer_links = 
    logo_url = 
    favicon_url = 