apiVersion: v1
data:
  grafana.ini: |
    [server]
    http_port = 3000
    root_url = http://localhost:3000/

    [security]
    admin_user = admin
    admin_password = grafana123

    [users]
    allow_sign_up = false

    [log]
    mode = console
    level = info

    [analytics]
    reporting_enabled = false
    check_for_updates = false
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"grafana.ini":"[server]\nhttp_port = 3000\nroot_url = http://localhost:3000/\n\n[security]\nadmin_user = admin\nadmin_password = grafana123\n\n[users]\nallow_sign_up = false\n\n[log]\nmode = console\nlevel = info\n\n[analytics]\nreporting_enabled = false\ncheck_for_updates = false\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"grafana-config","namespace":"monitoring"}}
  creationTimestamp: "2025-08-06T05:35:38Z"
  name: grafana-config
  namespace: monitoring
  resourceVersion: "54648010"
  uid: e7b3c4fb-cbb9-4b65-a0b7-225b18571f1e
